---
language: ruby
rvm:
  - 2.1.2
bundler_args: --without production development
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
addons:
  postgresql: "9.3"
