development:
  adapter: postgresql
  encoding: unicode
  database: bucket-dev
  pool: 5
  host: localhost
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bucket-test
  pool: 5
  host: localhost
  username: postgres
  password:
